x-network: &NETWORK
             "gqlgen-network"

version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - ./api:/app
    environment:
      - GO_ENV=development
      - APP_PORT=8080
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=dev
      - DB_PORT=3306
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    ports:
      - "8080:8080"
    networks:
      - *NETWORK
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://redis:6379
      - -wait
      - tcp://mysql:3306
      - -wait-retry-interval
      - 3s
    command: [ "sh", "./scripts/entrypoint.sh" ]
    depends_on:
      - redis
      - mysql
  redis:
    build:
      context: ./redis/docker
    networks:
      - *NETWORK
    ports:
      - "6379:6379"
  mysql:
    build:
      context: ./mysql/docker
    restart: always
    networks:
      - *NETWORK
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/volume:/var/lib/mysql:delegated
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_ROOT_PASSWORD=password
    command: --default-authentication-plugin=mysql_native_password
networks:
  gqlgen-network:
    driver: bridge