version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: ./remosis-api/Dockerfile.dev
    volumes:
      - ./remosis-api:/app
      - ~/.aws:/root/.aws
    environment:
      - PORT=8080
      - GO_ENV=development
      - DB_USER=root
      - DB_NAME=remosis_dev
      - DB_PASSWORD=password
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_MAXOPENCONNECTION=100
      - DB_MAXIDLECONNECTION=10
      - DB_CONNECTIONMAXLIFETIMEHOUR=1
      - TEST_DB_NAME=remosis_test
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=
      - REDIS_POOLSIZEPERCPU=10
      - REDIS_MINIDLECONNECTION=0
      - REDIS_POOLTIMEOUTSECONDS=4
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_NAMESPACE=${AUTH0_NAMESPACE}
      - SENDGRID_APIKEY=${SENDGRID_APIKEY}
      - SENDGRID_FROMADDRESS=${SENDGRID_FROMADDRESS}
      - SENDGRID_OPERATORCLIENTURL=${SENDGRID_OPERATORCLIENTURL}
      - AWS_S3BUCKETNAME=${AWS_S3BUCKETNAME}
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
  redis:
    build:
      context: ./redis/docker
    ports:
      - "6379:6379"
  mysql:
    build:
      context: ./mysql/docker
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/volume:/var/lib/mysql:delegated
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      # - MYSQL_DATABASE=remosis_dev
      - MYSQL_ROOT_PASSWORD=password
    platform: linux/x86_64
  # operator:
  #   build:
  #     context: .
  #     dockerfile: ./remosis-operator-proto/Dockerfile.dev
  #   volumes:
  #     - ./remosis-operator-proto:/app
  #   ports:
  #     - "8090:3000"

volumes:
  mysql_db:
    driver: local
