x-network: &NETWORK
             "gqlgen-network"

version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - ./api:/app
    environment:
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=
      - REDIS_POOLSIZEPERCPU=10
      - REDIS_MINIDLECONNECTION=0
      - REDIS_POOLTIMEOUTSECONDS=4
    ports:
      - "8080:8080"
    networks:
      - *NETWORK
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://redis:6379
      - -wait-retry-interval
      - 3s
    command: [ "sh", "./scripts/entrypoint.sh" ]
    depends_on:
      - redis
  redis:
    build:
      context: ./redis/docker
    networks:
      - *NETWORK
    ports:
      - "6379:6379"
networks:
  gqlgen-network:
    driver: bridge